name: reutilizando accion-simple-compuesta Node.js CI 
on:
  workflow_dispatch:
  push:
jobs:
  test:
    strategy:
        matrix:
         os: [ubuntu-latest]
    uses: amiguelGH/video-fsm-tres-reusable-action/.github/workflows/workflow_call.yml@main
    with:
      runner: ${{ matrix.os }}
