name: workflow_call Node.js Package

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
        
permissions:
  id-token: write
  contents: read
  pages: write
  
jobs:
  build-and-deploy:
    runs-on: ${{ inputs.runner }}
       echo "este es el runner ${{ runs-on }} ..1.. $runs-on ..2..   runs-on"
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Node  
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies    
        run: npm ci
      - name: Build Project
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          name: "github-pages"
          path: build

      - name: Deploy with gh-pages
        uses: actions/deploy-pages@v4
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: "github-pages"
